/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package de.detim.njustus.kafkaexample

import cats.effect._

object App extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = IO.println("hello world") >> IO(ExitCode.Success)
}
